services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      # Add Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      # Update and install Chrome
      apt-get update
      apt-get install -y google-chrome-stable
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
